# -*- coding: utf-8 -*-
"""exp 13 lab cv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MeL7AnfKbD4eA-7brV1p4L7J4qfRSWJx
"""

import cv2
import numpy as np
from google.colab import files
from google.colab.patches import cv2_imshow

# Upload image
uploaded = files.upload()

# Get uploaded filename automatically
filename = list(uploaded.keys())[0]

# Read image
img = cv2.imread(filename)

# Check if image loaded
if img is None:
    print("Image not found!")
else:
    rows, cols = img.shape[:2]

    src_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [0, rows - 1],
        [cols - 1, rows - 1]
    ])

    dst_points = np.float32([
        [0, 0],
        [cols - 1, 0],
        [0, int(0.7 * rows)],
        [cols - 1, int(0.7 * rows)]
    ])

    M, _ = cv2.findHomography(src_points, dst_points)

    homography_img = cv2.warpPerspective(img, M, (cols, rows))

    print("Original Image")
    cv2_imshow(img)

    print("Homography Transformed Image")
    cv2_imshow(homography_img)

    cv2.imwrite("transformation_using_Homography_Image.jpg", homography_img)